### ISSUE TITLE
Support comma-separated titles in prospect command

### ISSUE THREAD

**Issue by bernerdschaefer** [thoughtbot/clearbit#17]
It would be nice to be able to search titles when prospecting with:

```
$ clearbit prospect -title CEO,COO company.com
```

In addition to

```
$ clearbit prospect -title CEO -title COO company.com
```

Requested by @croaky in https://github.com/thoughtbot/clearbit/pull/15#discussion_r61967800.

**Comment by croaky** [comment]
Follow-up change in https://github.com/thoughtbot/clearbit/pull/23 addressed this
